language: php
matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: DB=mysql
#    - php: 7.0
#      env: DB=pgsql
#      addons:
#        postgresql: "9.4"
#    - php: 7.0
#      env: DB=pgsql
#      sudo: true
#      dist: trusty
#      addons:
#        postgresql: "9.5"
#    - php: 7.0
#      env: DB=mysql BEHAT=true
#    - php: 7.0
#      env: DB=pgsql BEHAT=true
#      addons:
#        postgresql: "9.4"
#    - php: 7.0
#      env: DB=pgsql BEHAT=true
#      sudo: true
#      dist: trusty
#      addons:
#        postgresql: "9.5"
#    - php: 5.6
#      env: DB=sqlite
#    - php: 5.5
#      env: DB=sqlite
cache:
  directories:
    - $HOME/.composer/cache
before_install:
  - cd ..
  - git clone https://github.com/neos/neos-development-distribution.git -b master
  - cd neos-development-distribution
  - export USER_GH_URL=https://github.com/$TRAVIS_REPO_SLUG
  - export USER_REPO_URL=$(echo "$USER_GH_URL" | sed 's/\//\\\//g' )
  - export NEOS_REPO=$(echo '"neos/neos-development-collection":"$TRAVIS_BRANCH as dev-master",')
  - env
  - export NEOS_REPLACE=$(echo "$NEOS_REPO" | sed 's/\//\\\//g')
  - env
  - sed  "1s/.*/{\"repositories\":[{\"type\":\"vvcs\",\"url\":\"$USER_REPO_URL\"}],/" composer.json >> composer.json_modified
  - cat composer.json_modified
  - sed "s/neos\/neos-development-collection.*/$NEOS_REPLACE/g" composer.json_modified > composer.json
install:
  - composer self-update -q
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - composer install --no-progress --no-interaction
  - composer update --no-progress --no-interaction
before_script:
  - phpenv config-rm xdebug.ini
  - echo 'date.timezone = "Antarctica/Troll"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'opcache.fast_shutdown = 0' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'opcache.enable_cli = 0' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'zend.enable_gc = 0' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'report_zend_debug = 0' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'report_memleaks = 0' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - cp Configuration/Settings.yaml.example Configuration/Settings.yaml
  - Build/BuildEssentials/TravisCi/SetupDatabase.sh
  - cp Configuration/Settings.yaml Configuration/Testing/
  - if [ "$BEHAT" = "true" ]; then composer install -d Build/Behat; fi
script:
  - if [ "$BEHAT" != "true" ]; then bin/phpunit --colors -c Build/BuildEssentials/PhpUnit/UnitTests.xml; fi
  - if [ "$BEHAT" != "true" ]; then bin/phpunit --colors --stop-on-failure -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml --testsuite "Neos tests"; fi
  - if [ "$BEHAT" = "true" ]; then bin/behat --ansi --stop-on-failure -f progress -c Packages/Neos/TYPO3.Neos/Tests/Behavior/behat.yml.dist --tags ~@browser; fi
  - if [ "$BEHAT" = "true" ]; then bin/behat --ansi --stop-on-failure -f progress -c Packages/Neos/TYPO3.TYPO3CR/Tests/Behavior/behat.yml.dist; fi