language: php
matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: DB=mysql
    - php: 7.0
      env: DB=pgsql
      addons:
        postgresql: "9.4"
    - php: 7.0
      env: DB=pgsql
      sudo: true
      dist: trusty
      addons:
        postgresql: "9.5"
    - php: 7.0
      env: DB=mysql BEHAT=true
    - php: 7.0
      env: DB=pgsql BEHAT=true
      addons:
        postgresql: "9.4"
    - php: 7.0
      env: DB=pgsql BEHAT=true
      sudo: true
      dist: trusty
      addons:
        postgresql: "9.5"
    - php: 5.6
      env: DB=sqlite
    - php: 5.5
      env: DB=sqlite
cache:
  directories:
    - $HOME/.composer/cache
before_install:
  - cd ..
  - git clone https://github.com/neos/neos-development-distribution.git -b master
  - cd neos-development-distribution
install:
  - composer self-update -q
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
script:
  - env